version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8000:80"
    networks:
      - nginx-network
    depends_on:
      - products_api
      - users_api

  products_api:
    container_name: products_api
    build:
      context: ./backends/products/
      dockerfile: Dockerfile
    networks:
      - nginx-network

  users_api:
    container_name: users_api
    build:
      context: ./backends/users/
      dockerfile: Dockerfile
    networks:
      - nginx-network

  sales_api:
    container_name: sales_api
    build:
      context: ./backends/sales/
      dockerfile: Dockerfile
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
